version: "3"

networks:
  app-tier:
    driver: bridge

services:
  todoapi:
    build: .
    networks:
      - app-tier
    ports:
      - "8090:8090"
    depends_on:
      - dbpgsql
    volumes:
      - "./:/todoapi/src/app"
  dbpgsql:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier
